### ISSUE TITLE
Doesn't work with some valid Dein installation paths

### ISSUE THREAD

**Issue by byronalley** [takkii/totolot#3]
I was having trouble with totolot crashing and discovered it's because I was using a different Dein installation directory (.local/share/dein) based on the examples at https://github.com/Shougo/dein.vim:

> For example, ~/.vim/bundles or ~/.cache/dein or ~/.local/share/dein

一部の有効なDeinインストールパスでは機能しません。

（これは自動翻訳です。申し訳ありませんが、私の日本語はとても悪いです！）

totolotのクラッシュに問題があり、https：//github.com/Shougo/dein.vimの例に基づいて別のDeinインストールディレクトリ（.local / share / dein）を使用していたことが原因であることがわかりました。

> For example, ~/.vim/bundles or ~/.cache/dein or ~/.local/share/dein

**Comment by takkii** [comment]
I agree that Totlot will evolve.
I was happy to take in the PR. Close the issue.

トトロットが進化していくことに同意します。
PRを喜んで、取り込みました。イシューを閉じます。

**Comment by byronalley** [comment]
Awesome, thanks!

素晴らしいです、ありがとう。
